export const splitterModels = [
  {
    model: "NXS-2P-0.5-8",
    ways: 2,
    frequency: "0.5 – 8 GHz",
    insertionLoss: "≤ 1.2 dB",
    isolationMin: "20 dB",
    isolationTyp: "25 dB",
    vswrCombined: "1.20 (Typ) / 1.30 (Max)",
    vswrDistribution: "1.15 (Typ) / 1.25 (Max)",
    amplitudeBalance: "± 0.2 dB",
    phaseBalance: "± 3°",
    impedance: "50 Ohms",
    powerSplitter: "30 W",
    powerCombiner: "2 W",
    dimensions: "51.7 × 30 × 10 mm",
    connectors: "SMA-Female",
    weight: "44 g",
  },
  {
    model: "NXS-2P-0.5-18",
    ways: 2,
    frequency: "0.5 – 18 GHz",
    insertionLoss: "≤ 2.5 dB",
    isolationMin: "15 dB",
    isolationTyp: "24 dB",
    vswrCombined: "1.30 (Typ) / 2.0 (Max)",
    vswrDistribution: "1.20 (Typ) / 1.50 (Max)",
    amplitudeBalance: "± 0.8 dB",
    phaseBalance: "± 8°",
    impedance: "50 Ohms",
    powerSplitter: "30 W",
    powerCombiner: "1 W",
    dimensions: "51.7 × 30 × 10 mm",
    connectors: "SMA-Female",
    weight: "44 g",
  },
  {
    model: "NXS-2P-28",
    ways: 2,
    frequency: "2 – 8 GHz",
    insertionLoss: "≤ 0.6 dB",
    isolationMin: "20 dB",
    isolationTyp: "26 dB",
    vswrCombined: "1.14 (Typ) / 1.25 (Max)",
    vswrDistribution: "1.10 (Typ) / 1.20 (Max)",
    amplitudeBalance: "± 0.2 dB",
    phaseBalance: "± 3°",
    impedance: "50 Ohms",
    powerSplitter: "30 W",
    powerCombiner: "2 W",
    dimensions: "28 × 28 × 10 mm",
    connectors: "SMA-Female",
    weight: "23 g",
  },
  {
    model: "NXS-4P-0.5-18",
    ways: 4,
    frequency: "0.5 – 18 GHz",
    insertionLoss: "≤ 2.5 dB",
    isolationMin: "15 dB",
    isolationTyp: "24 dB",
    vswrCombined: "1.30 (Typ) / 2.0 (Max)",
    vswrDistribution: "1.20 (Typ) / 1.50 (Max)",
    amplitudeBalance: "± 0.8 dB",
    phaseBalance: "± 8°",
    impedance: "50 Ohms",
    powerSplitter: "30 W",
    powerCombiner: "1 W",
    dimensions: "163 × 68 × 10 mm",
    connectors: "SMA-Female",
    weight: "305 g",
  },
  {
    model: "NXS-4P-28",
    ways: 4,
    frequency: "2 – 8 GHz",
    insertionLoss: "≤ 1.0 dB",
    isolationMin: "20 dB",
    isolationTyp: "25 dB",
    vswrCombined: "1.16 (Typ) / 1.25 (Max)",
    vswrDistribution: "1.14 (Typ) / 1.20 (Max)",
    amplitudeBalance: "± 0.3 dB",
    phaseBalance: "± 4°",
    impedance: "50 Ohms",
    powerSplitter: "30 W",
    powerCombiner: "2 W",
    dimensions: "50 × 56 × 10 mm",
    connectors: "SMA-Female",
    weight: "64 g",
  },
  {
    model: "NXS-8P-28",
    ways: 8,
    frequency: "2 – 8 GHz",
    insertionLoss: "≤ 1.5 dB",
    isolationMin: "18 dB",
    isolationTyp: "25 dB",
    vswrCombined: "1.16 (Typ) / 1.35 (Max)",
    vswrDistribution: "1.14 (Typ) / 1.25 (Max)",
    amplitudeBalance: "± 0.4 dB",
    phaseBalance: "± 5°",
    impedance: "50 Ohms",
    powerSplitter: "30 W",
    powerCombiner: "2 W",
    dimensions: "63 × 108 × 10 mm",
    connectors: "SMA-Female",
    weight: "160 g",
  },
];
