export const meshModels = [
  {
    id: "nxa-b4p",
    model: "NXA-B4P",
    name: "Mesh Attenuator",
    frequencyText: "200 - 8000 MHz",
    overview:
      "The NXA-B4P programmable mesh attenuator is a fully shielded, high-performance, digitally controlled RF attenuator system featuring robust and repeatable digital attenuation. It stands out with a user-friendly GUI, customizable fading profiles, and extensive connectivity options, enclosed in a compact 1RU design.",
    image: "/images/mesh4.webp",
    features: [
      "Extended Frequency Range: Operates across a broad spectrum from 200 MHz to 8 GHz, ensuring versatility for a wide array of testing applications.",
      "24/7 Operation: Engineered for continuous use, supporting fully automated testing workflows to maximize efficiency and reliability in mission-critical environments.",
      "Shielded and Precise: Complete shielding ensures highly accurate and interference-free measurements, ideal for precision testing in demanding RF environments.",
      "Customizable Topologies: Tailored to customer specifications, supporting multiple network topologies for enhanced flexibility and optimized test setups.",
      "High Dynamic Range: Offers up to 95 dB of attenuation with fine-grain control, adjustable in 0.25 dB increments, delivering exceptional precision for signal fading and attenuation simulations.",
      "Tailored User Interface: Custom-designed software interfaces align with specific customer needs, providing an intuitive and efficient control experience for streamlined operations.",
    ],
    applications: [
      "Wi-Fi communication systems",
      "Cellular systems (5G/4G/3G/2G)",
      "MIMO, Multipoint Radio Fading",
      "Automated Test Equipment (ATE)",
    ],
    specifications: [
      {
        parameter: "Frequency Range (MHz)",
        min: "200",
        typ: "",
        max: "8000",
        unit: "MHz",
      },
      { parameter: "Impedance", min: "", typ: "50", max: "", unit: "Ω" },
      {
        parameter: "Channel Inputs/Outputs",
        min: "",
        typ: "4",
        max: "",
        unit: "",
      },
      {
        parameter: "Attenuation Range",
        min: "",
        typ: "95",
        max: "",
        unit: "dB",
      },
      { parameter: "Shielding", min: "", typ: "90", max: "", unit: "dB" },
      {
        parameter: "Isolation between Channels",
        min: "",
        typ: "90",
        max: "",
        unit: "dB",
      },
      { parameter: "Step Size", min: "", typ: "0.25", max: "", unit: "dB" },
      {
        parameter: "Insertion Loss (< 2 GHz)",
        min: "",
        typ: "18",
        max: "",
        unit: "dB",
      },
      {
        parameter: "Insertion Loss (< 4 GHz)",
        min: "",
        typ: "22",
        max: "",
        unit: "dB",
      },
      {
        parameter: "Insertion Loss (< 7.5 GHz)",
        min: "",
        typ: "28",
        max: "",
        unit: "dB",
      },
      {
        parameter: "Attenuation Accuracy",
        min: "0.25",
        typ: "1.5",
        max: "",
        unit: "dB",
      },
      { parameter: "Switching Speed", min: "", typ: "2", max: "", unit: "µs" },
      {
        parameter: "Maximum Input Level (operating)",
        min: "",
        typ: "+28",
        max: "",
        unit: "dBm",
      },
      {
        parameter: "Maximum Input Level (absolute max)",
        min: "",
        typ: "+33",
        max: "",
        unit: "dBm",
      },
      { parameter: "Input IP3", min: "", typ: "58", max: "", unit: "dBm" },
      {
        parameter: "Operating modes",
        min: "",
        typ: "Uni/Bi-Directional",
        max: "",
        unit: "",
      },
      {
        parameter: "Control",
        min: "",
        typ: "GUI control or APIs",
        max: "",
        unit: "",
      },
      {
        parameter: "Power",
        min: "",
        typ: "Power over Ethernet (PoE)",
        max: "",
        unit: "",
      },
      {
        parameter: "Operating Temperature",
        min: "-30",
        typ: "",
        max: "+70",
        unit: "°C",
      },
      { parameter: "RF connectors", min: "", typ: "SMA", max: "", unit: "" },
      {
        parameter: "Control Interface",
        min: "",
        typ: "Ethernet or USB",
        max: "",
        unit: "",
      },
      {
        parameter: "Operating System",
        min: "",
        typ: "Windows, Linux and Mac",
        max: "",
        unit: "",
      },
    ],
    environmental: [
      {
        parameter: "Power Requirements",
        conditions: "+5VDC (from USB port) – 1.1 Amps",
      },
      {
        parameter: "Environmental",
        conditions: "Operating Temperature: 0°C to +40°C",
      },
      {
        parameter: "Physical Connections",
        conditions:
          "Power Connector: USB\nControl: USB/Ethernet\nRF Connectors: SMA – female",
      },
      {
        parameter: "Mechanical",
        conditions:
          "Size (1RU): 17.0 x 13 x 1.75 inches\nWeight: 10 lbs / 4.5 kg",
      },
    ],
  },
  {
    id: "nxa-b9p",
    model: "NXA-B9P",
    name: "9 Port Mesh Attenuator",
    frequencyText: "200 to 8000 MHz",
    overview:
      "The NXA-B9P programmable mesh attenuator is a fully shielded, high-performance, digitally controlled RF attenuator system featuring 36 channels. It is designed for automated RF testing applications that require precise signal power control. The NXA-B9P delivers excellent attenuation accuracy, a wide dynamic range, and fast response speed. Its superior performance is achieved through a high-precision attenuator design along with thorough calibration.",
    image: "/images/mesh9.webp",
    features: [
      "Wideband Frequency Coverage: Supports operation from 200 MHz to 8 GHz, enabling testing across Wi-Fi, cellular, and broadband RF systems.",
      "Designed for Continuous Operation: Built for 24/7 unattended use, making it ideal for fully automated and long-duration RF test environments.",
      "Fully Shielded Architecture: A completely shielded RF enclosure ensures accurate, low-interference measurements across all mesh paths.",
      "Full 9-Port Mesh Topology: Implements a non-blocking 9-port mesh with 36 independent attenuation paths, configurable to support diverse test scenarios.",
      "High Dynamic Attenuation Range: Provides up to 95 dB attenuation with 0.25 dB resolution, enabling precise and repeatable RF fading and path-loss emulation.",
      "Intuitive Control Software: Offers a user-friendly GUI with programmable APIs, allowing efficient manual control and seamless automation.",
    ],
    applications: [
      "Wi-Fi 7/6E/6 and IoT testing",
      "5G/4G/3G/2G cellular system validation",
      "MIMO and multipoint RF fading simulation",
      "Automated test equipment (ATE) integration",
      "R&D characterization and high-volume production testing",
    ],
    specifications: [
      {
        parameter: "Frequency Range (MHz)",
        min: "200",
        typ: "",
        max: "8000",
        unit: "MHz",
      },
      { parameter: "Impedance", min: "", typ: "50", max: "", unit: "Ω" },
      { parameter: "Number of RF Ports", min: "", typ: "9", max: "", unit: "" },
      {
        parameter: "Attenuation Range",
        min: "",
        typ: "95",
        max: "",
        unit: "dB",
      },
      { parameter: "Shielding", min: "", typ: "90", max: "", unit: "dB" },
      {
        parameter: "Isolation between Channels",
        min: "",
        typ: "90",
        max: "",
        unit: "dB",
      },
      { parameter: "Step Size", min: "", typ: "0.25", max: "", unit: "dB" },
      {
        parameter: "Insertion Loss (< 3 GHz)",
        min: "",
        typ: "24",
        max: "",
        unit: "dB",
      },
      {
        parameter: "Insertion Loss (< 6 GHz)",
        min: "",
        typ: "29",
        max: "",
        unit: "dB",
      },
      {
        parameter: "Insertion Loss (< 8 GHz)",
        min: "",
        typ: "32",
        max: "",
        unit: "dB",
      },
      {
        parameter: "Attenuation Accuracy",
        min: "±0.25",
        typ: "±1.5",
        max: "",
        unit: "dB",
      },
      { parameter: "Switching Speed", min: "", typ: "2", max: "", unit: "µs" },
      {
        parameter: "Maximum Input Level (operating)",
        min: "",
        typ: "+28",
        max: "",
        unit: "dBm",
      },
      {
        parameter: "Maximum Input Level (absolute max)",
        min: "",
        typ: "+33",
        max: "",
        unit: "dBm",
      },
      {
        parameter: "Operating modes",
        min: "",
        typ: "Uni/Bi-Directional, GUI control or APIs",
        max: "",
        unit: "",
      },
      {
        parameter: "Operating Temperature",
        min: "-30",
        typ: "",
        max: "+70",
        unit: "°C",
      },
      { parameter: "RF connectors", min: "", typ: "SMA", max: "", unit: "" },
      {
        parameter: "Control Interface",
        min: "",
        typ: "Ethernet or USB",
        max: "",
        unit: "",
      },
      {
        parameter: "Operating System",
        min: "",
        typ: "Windows, Linux and Mac",
        max: "",
        unit: "",
      },
    ],
    environmental: [
      {
        parameter: "Power Requirements",
        conditions: "100 – 240 V AC, 50/60 Hz",
      },
      {
        parameter: "Environmental Conditions",
        conditions: "Operating Temperature: 0°C to +40°C",
      },
      {
        parameter: "Physical Connections",
        conditions:
          "Power Connector: Power Cord\nControl: USB/Ethernet\nRF Connectors: SMA – female",
      },
      {
        parameter: "Mechanical",
        conditions:
          "Size (3RU): 17.0 × 18 × 5.23 inches\nWeight: 32 lbs / 14.5kg",
      },
    ],
  },
];

export const meshModelMap = Object.fromEntries(
  meshModels.map((model) => [model.id, model]),
);
