export const matrixModels = [
  {
    model: "NXA-B168M",
    name: "Matrix Attenuator",
    frequencyText: "200 - 8000 MHz",
    overview:
      "The NXA-B168M Matrix Attenuator offers robust and repeatable digital attenuation with user-friendly GUI controls. Supporting Windows and Linux, it features customizable fading profiles, USB and Ethernet control options, all housed in a compact design.",
    image:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1600&q=80",
    features: [
      "Extended Frequency Range: Operates across a broad spectrum from 200 MHz to 8 GHz, ensuring versatility for a wide array of testing applications.",
      "24/7 Operation: Engineered for continuous use, supporting fully automated testing workflows to maximize efficiency and reliability in mission-critical environments.",
      "Shielded and Precise: Complete shielding ensures highly accurate and interference-free measurements, ideal for precision testing in demanding RF environments.",
      "Customizable Topologies: Tailored to customer specifications, supporting multiple network topologies for enhanced flexibility and optimized test setups.",
      "High Dynamic Range: Offers up to 95 dB of attenuation with fine-grain control, adjustable in 0.25 dB increments, delivering exceptional precision for signal fading and attenuation simulations.",
      "Tailored User Interface: Custom-designed software interfaces align with specific customer needs, providing an intuitive and efficient control experience for streamlined operations.",
    ],
    applications: [
      "Wi-Fi communication systems",
      "Cellular systems (5G/4G/3G/2G)",
      "MIMO, Multipoint Radio Fading",
      "Automated Test Equipment (ATE)",
    ],
    specifications: [
      {
        parameter: "Frequency Range (MHz)",
        min: "200",
        typ: "",
        max: "8000",
        unit: "MHz",
      },
      { parameter: "Impedance", min: "", typ: "50", max: "", unit: "Ω" },
      {
        parameter: "Channel Inputs/Outputs",
        min: "",
        typ: "16x8",
        max: "",
        unit: "",
      },
      {
        parameter: "Attenuation Range",
        min: "",
        typ: "95",
        max: "",
        unit: "dB",
      },
      { parameter: "Shielding", min: "", typ: "90", max: "", unit: "dB" },
      {
        parameter: "Isolation between Channels",
        min: "",
        typ: "90",
        max: "",
        unit: "dB",
      },
      { parameter: "Step Size", min: "", typ: "0.25", max: "", unit: "dB" },
      {
        parameter: "Insertion Loss (< 2 GHz)",
        min: "",
        typ: "21",
        max: "",
        unit: "dB",
      },
      {
        parameter: "Insertion Loss (< 4 GHz)",
        min: "",
        typ: "26",
        max: "",
        unit: "dB",
      },
      {
        parameter: "Insertion Loss (< 7.5 GHz)",
        min: "",
        typ: "30",
        max: "",
        unit: "dB",
      },
      {
        parameter: "Attenuation Accuracy",
        min: "0.25",
        typ: "1.5",
        max: "",
        unit: "dB",
      },
      { parameter: "Switching Speed", min: "", typ: "2", max: "", unit: "µs" },
      {
        parameter: "Maximum Input Level (operating)",
        min: "",
        typ: "+28",
        max: "",
        unit: "dBm",
      },
      {
        parameter: "Maximum Input Level (absolute max)",
        min: "",
        typ: "+33",
        max: "",
        unit: "dBm",
      },
      { parameter: "Input IP3", min: "", typ: "58", max: "", unit: "dBm" },
      {
        parameter: "Operating modes",
        min: "",
        typ: "Uni/Bi-Directional",
        max: "",
        unit: "",
      },
      {
        parameter: "Control",
        min: "",
        typ: "GUI control or APIs",
        max: "",
        unit: "",
      },
      {
        parameter: "Power",
        min: "",
        typ: "Power over Ethernet (PoE)",
        max: "",
        unit: "",
      },
      {
        parameter: "Operating Temperature",
        min: "-30",
        typ: "",
        max: "+70",
        unit: "°C",
      },
      { parameter: "RF connectors", min: "", typ: "SMA", max: "", unit: "" },
      {
        parameter: "Control Interface",
        min: "",
        typ: "Ethernet or USB",
        max: "",
        unit: "",
      },
      {
        parameter: "Operating System",
        min: "",
        typ: "Windows, Linux and Mac",
        max: "",
        unit: "",
      },
    ],
    environmental: [
      {
        parameter: "Power Requirements",
        conditions: "+5VDC (from USB port) – 1.1 Amps",
      },
      {
        parameter: "Environmental",
        conditions: "Operating Temperature: 0°C to +40°C",
      },
      {
        parameter: "Physical Connections",
        conditions:
          "Power Connector: USB\nControl: USB/Ethernet\nRF Connectors: SMA – female",
      },
      {
        parameter: "Mechanical",
        conditions:
          "Size (3RU): 17.0 × 18 × 5.23 inches\nWeight: 32 lbs / 14.5 kg",
      },
    ],
  },
];
